### ISSUE TITLE
Support more uevent actions

### ISSUE THREAD

**Issue by illiliti** [skarnet/mdevd#3]
This feature isn't compatible with `busybox mdev` (and probably upcoming `toybox mdev`). However, it is actually useful to have the ability to run commands on change action. The one of possible use cases is a battery capacity notifier. See https://github.com/Ventto/batify.

Proposed syntax:
```
# do something on ACTION=change
<rule> <own>:<grp> <perm> %<cmd>
```

**Comment by skarnet** [comment]
That looks useful indeed, but it requires modifying the transition table, which is a lot of work, so don't expect the change to happen right away.

Do you know whether there are also cases where the kernel sends "move", "online", "offline", "bind" or "unbind" actions in the uevent as well? If I'm going to modify the transition table, I'd rather do it only once.

**Comment by illiliti** [comment]
Documentation about uevent actions... well, about uevents in general literally doesn't exist. I had to read kernel code, so I may be wrong somewhere.

* As far as I understand, `bind` is triggered when a physical device being linked to a kernel module.

1. user connected device
2. `add` action is triggered and sent to netlink
3. `mdevd` parses uevent message and calls `modprobe $MODALIAS` to load module
4. `bind` action is triggered and sent to netlink

* The `unbind` action usually caused by running `rmmod`.

1. user unloaded module that has linked device
2. `unbind` action is triggered and sent to netlink
3. `remove` action is triggered and sent to netlink

* The `online` and `offline` actions are very driver specific. Most of drivers uses these actions to signal device state to gracefully handle cleanups or synchronizations(locking).

* The `move` action intended to signal that device has a new location. I.e. renaming wlan0 will raise uevent with this action.

My conclusion is that all these actions may have use cases, so I think it's worth to consider adding them to transition table.

**Comment by skarnet** [comment]
Yeah, I know everything _may_ have a use case, my question was about real usage in the real world. For instance, there are discussions on udevd about the right way to handle `unbind` events, for instance - the consensus seems to be that userland should ignore them. If providing a hook for a certain type of event is a trap, I'd rather avoid putting effort into it.

Anyway, this is pretty moot, because adding support for another action requires changing the mdevd logic too. It would impact more than the transition table, so I may as well go for maximum expressive power if I make this change.

No promises, and especially no promises on a date, but I'll definitely think about it and implement it when I find a suitable way of expressing more flexible action filters.

**Comment by skarnet** [comment]
So a way to implement more actions without breaking existing semantics, and without having to modify the transition table too much, would be to have the `*` and `&` directives (which currently catch both `add` and `remove`) actually catch _everything_, and run the script with the action name either as an argument, or as the value of the `ACTION` environment variable. Would that be practical for you?
Edit: the script runs with the whole event in its environment anyway, so ACTION is already there. It's just a matter of making `*` and `&` scripts run on all action types instead of only `add` and `remove`.

**Comment by skarnet** [comment]
The approach I suggested in my previous comment made it actually super easy to support all action types. It is now implemented in the master branch. To handle `ACTION=change`, use a `*shell script` or a `&execline script` directive, and in your script, filter on the value of the ACTION environment variable.

Please tell me if it's working for you.

**Comment by illiliti** [comment]
It works, thanks!
