### ISSUE TITLE
Add support for /etc/mdevd.d config directory

### ISSUE THREAD

**Issue by illiliti** [skarnet/mdevd#6]
I propose to add support for /etc/mdevd.d for user configs and /lib/mdevd.d for package-specific configs.
/lib/mdevd.d is useful for packages that want to install rules without user interaction. The idea is similar to /lib/udev/rules.d

This proposal definitely complicates mdevd. On the other side, it also makes mdevd a more usable alternative to udev. Anyway, I'd like to hear your thoughts.

**Comment by skarnet** [comment]
If you've so much as taken a single glance at the mdevd config parser, you already know that's not going to happen in the mdevd code itself. 😂

However, as with every config file, that problem can be easily solved by scripting, and most distros already do this for a lot of daemons: they provide a script that preprocesses the config directory/directories, concatenates all the files, and dump everything into the single configuration file that is read by the daemon itself. Given that the details of what configuration directories to read and in what order are pure policy, I think it's reasonable to leave that preprocessing step to distributions.

**Comment by illiliti** [comment]
> If you've so much as taken a single glance at the mdevd config parser, you already know that's not going to happen in the mdevd code itself. :joy:

It's overly complicated mess which is better to not touch at all. I get that :joy:

> they provide a script that preprocesses the config directory/directories, concatenates all the files, and dump everything into the single configuration file.

The similar approach has been considered in Alpine Linux regarding OpenDoas and seems like people don't like this idea. I don't like this idea either, to be honest. Although, I appreciate your decision

**Comment by skarnet** [comment]
Far from an overly complicated mess, it's the _simplest and most efficient way_ to parse a given language. However, it means the parser is quite static, as in, it is difficult to change the language after the parser is written. Adding a file/directory includer would be a significant change to the language, and that would mean rewriting the parser entirely, which is a huge amount of work I'm not willing to do.

If anything, I would write a preprocessor myself and add it to the mdevd package. There is no reason not to like preprocessors; my perception is that the dislike comes from a "monoprocess" culture, where one binary must do all the work in a holistic way - to me, that is antithetical to the Unix philosophy, where binaries interact with the system in a harmonious way because the system primitives were designed for it, and a service is provided not by one unique binary, but by a set of cooperating processes.
